version = 0.1

[dev.deploy.parameters]
stack_name = "micro-credentialing-backend-dev"
resolve_s3 = true
s3_prefix = "micro-credentialing-backend-dev"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "CognitoUserPoolId=\"us-east-1_CkcMQmOst\" Environment=\"dev\""
tags = "Environment=\"dev\" Project=\"micro-credentialing\""

[dev.global.parameters]
region = "us-east-1"